### ISSUE TITLE
Make it clear that the underlying [securestring] type provides no encryption on Unix 

### ISSUE THREAD

**Issue by mklement0** [iRon7/HiddenString#6]
This is especially problematic with persisting a `.ToBase64Cypher()` return value inside a script on Unix, as it is trivial to convert it back to plain text.

I suggest updating at least the read-me, but a runtime warning is probably also called for.

**Comment by iRon7** [comment]
Added:

* note in readme:

> **Note**
>
> Note that per DotNet, the contents of a SecureString are not encrypted on non-Windows systems.

* Throw error when there is no DPAPI encryption available
